import { MaterialCategory } from './types'

export const STEEL_MATERIALS: MaterialCategory = {
  name: "Carbon & Alloy Steels",
  grades: {
    // Structural Steels
    a36: { 
      name: "A36 Structural Steel", 
      density: 7.85, 
      color: "bg-gray-600",
      yieldStrength: 250,
      tensileStrength: 400,
      elasticModulus: 200,
      poissonRatio: 0.26,
      hardness: "120 HB",
      thermalExpansion: 11.7,
      thermalConductivity: 50,
      specificHeat: 490,
      meltingPoint: 1425,
      relativeCost: 1,
      availability: 'excellent' as const,
      standards: ["ASTM A36", "EN S235"],
      applications: ["Building frames", "Bridges", "General construction"],
      temperatureCoefficient: -0.0004
    },
    a572: { 
      name: "A572 Grade 50 HSLA", 
      density: 7.85, 
      color: "bg-gray-700",
      yieldStrength: 345,
      tensileStrength: 450,
      elasticModulus: 200,
      poissonRatio: 0.26,
      hardness: "140 HB",
      thermalExpansion: 11.7,
      thermalConductivity: 50,
      specificHeat: 490,
      meltingPoint: 1425,
      relativeCost: 2,
      availability: 'excellent' as const,
      standards: ["ASTM A572", "ASTM A992"],
      applications: ["High-rise buildings", "Heavy construction", "Pressure vessels"],
      temperatureCoefficient: -0.0004
    },
    a992: { 
      name: "A992 Grade 50 Wide Flange", 
      density: 7.85, 
      color: "bg-gray-800",
      yieldStrength: 345,
      tensileStrength: 450,
      elasticModulus: 200,
      poissonRatio: 0.26,
      hardness: "140 HB",
      thermalExpansion: 11.7,
      thermalConductivity: 50,
      specificHeat: 490,
      meltingPoint: 1425,
      relativeCost: 2,
      availability: 'excellent' as const,
      standards: ["ASTM A992"],
      applications: ["Structural beams", "Building frames", "Infrastructure"],
      temperatureCoefficient: -0.0004
    },
    mild: { 
      name: "Mild Steel (1018)", 
      density: 7.87, 
      color: "bg-gray-500",
      yieldStrength: 370,
      tensileStrength: 440,
      elasticModulus: 205,
      poissonRatio: 0.29,
      hardness: "126 HB",
      thermalExpansion: 11.7,
      thermalConductivity: 51,
      specificHeat: 486,
      meltingPoint: 1415,
      relativeCost: 1,
      availability: 'excellent' as const,
      standards: ["AISI 1018", "SAE 1018"],
      applications: ["General machining", "Shafts", "Gears"],
      temperatureCoefficient: -0.0004
    },
    
    // High Strength Steels
    a514: {
      name: "A514 High Strength Steel",
      density: 7.85,
      color: "bg-red-700",
      yieldStrength: 690,
      tensileStrength: 760,
      elasticModulus: 200,
      poissonRatio: 0.26,
      hardness: "230 HB",
      thermalExpansion: 11.7,
      thermalConductivity: 50,
      specificHeat: 490,
      meltingPoint: 1425,
      relativeCost: 3,
      availability: 'good' as const,
      standards: ["ASTM A514"],
      applications: ["Cranes", "Earth moving equipment", "Military vehicles"],
      temperatureCoefficient: -0.0004
    },
    
    // Tool Steels
    d2: {
      name: "D2 Tool Steel",
      density: 7.7,
      color: "bg-purple-700",
      yieldStrength: 1700,
      tensileStrength: 1900,
      elasticModulus: 210,
      poissonRatio: 0.27,
      hardness: "60 HRC",
      thermalExpansion: 11.2,
      thermalConductivity: 20,
      specificHeat: 460,
      meltingPoint: 1425,
      relativeCost: 4,
      availability: 'fair' as const,
      standards: ["AISI D2", "DIN 1.2379"],
      applications: ["Dies", "Punches", "Cutting tools"],
      temperatureCoefficient: -0.0003
    },
  }
}